[tool.poetry]
name = "aas-pydantic"
version = "0.1.3"
description = "aas-pydantic is a package that combines the basyx python sdk for handling Asset Administration Shells (AAS) with pydantic Basemodels for fast and easy modeling and transformation of pydantic models and AAS."
authors = ["Sebastian Behrendt <sebastianbehrendt97@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
basyx-python-sdk = "^2.0.0"
pydantic = "^2.10.1"
stringcase = "^1.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
black = "^24.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
